version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.gpu_models
    volumes:
      - ./app/app_gpu_models.py:/app/app_gpu_models.py
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]


  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
